version: '3.1'
services:
  mysql:
    image: mysql:5.7.22
    ports: ["8888:3306"]
    hostname: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=Users
  web:
    build: pictolearn-web
    image: pictolearn-web
   # ports: ["5555:8080"]
    hostname: web
    tty: true
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DB_PORT=tcp://mysql:3306  
  dispatcher:
    build: pictolearn-dispatcher
    image: pictolearn-dispatcher
    ports: ["1111:8080"]
    hostname: dispatcher
    tty: true
    environment:
      - CATALINE_BASE=/opt/tomcat
      - CATALINE_HOME=/opt/tomcat
    depends_on:
      - web